#!/bin/bash
# The input method requires the use of the xcb platform environment in the wayland environment
# However, it cannot affect the entire system environment

export QT_QPA_PLATFORM=xcb
exec /usr/bin/kylin-virtual-keyboard 
unset QT_QPA_PLATFORM
